# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='\u0427\u0430\u0441 \u043f\u043e\u0447\u0430\u0442\u043a\u0443 \u0437\u0430\u043d\u044f\u0442\u0442\u044f')),
                ('subject', models.CharField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u043f\u0430\u0440\u0438')),
                ('auditory', models.CharField(max_length=16, verbose_name='\u0410\u0443\u0434\u0438\u0442\u043e\u0440\u0456\u044f')),
                ('teacher', models.CharField(max_length=128, verbose_name='\u0412\u0438\u043a\u043b\u0430\u0434\u0430\u0447')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043d\u044f\u0442\u0442\u044f',
                'verbose_name_plural': '\u0417\u0430\u043d\u044f\u0442\u0442\u044f',
            },
        ),
        migrations.CreateModel(
            name='CurriculumDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='\u041d\u0430\u0432\u0447\u0430\u043b\u044c\u043d\u0438\u0439 \u0434\u0435\u043d\u044c')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0432\u0447\u0430\u043b\u044c\u043d\u0438\u0439 \u0434\u0435\u043d\u044c',
                'verbose_name_plural': '\u041d\u0430\u0432\u0447\u0430\u043b\u044c\u043d\u0456 \u0434\u043d\u0456',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='fb_bot.CurriculumDay'),
        ),
    ]
