# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumday',
            name='day',
            field=models.DateField(unique=True, verbose_name='\u041d\u0430\u0432\u0447\u0430\u043b\u044c\u043d\u0438\u0439 \u0434\u0435\u043d\u044c'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together=set([('day', 'time')]),
        ),
    ]
