# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0002_auto_20170910_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='type',
            field=models.CharField(default='\u041b\u0435\u043a\u0446\u0456\u044f', max_length=32, verbose_name='\u0422\u0438\u043f \u0437\u0430\u043d\u044f\u0442\u0442\u044f'),
        ),
    ]
