# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0003_curriculum_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.CharField(choices=[('mattai', '\u041c\u0430\u0442\u0435\u043c\u0430\u0442\u0438\u0447\u043d\u0456 \u0442\u0430 \u0456\u043c\u0456\u0442\u0430\u0446\u0456\u0439\u043d\u0456 \u043c\u043e\u0434\u0435\u043b\u0456 \u0441\u043a\u043b\u0430\u0434\u043d\u0438\u0445 \u0441\u0438\u0441\u0442\u0435\u043c'), ('prykte', '\u041f\u0440\u0438\u043a\u043b\u0430\u0434\u043d\u0430 \u0442\u0435\u043e\u0440\u0456\u044f \u0433\u0440\u0430\u0444\u0456\u0432'), ('infsys', '\u0406\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u0439\u043d\u043e-\u0443\u043f\u0440\u0430\u0432\u043b\u044f\u044e\u0447\u0456 \u0441\u0438\u0441\u0442\u0435\u043c\u0438 \u0456 \u0442\u0435\u0445\u043d\u043e\u043b\u043e\u0433\u0456\u0457 \u0432 \u0431\u0443\u0434\u0456\u0432\u043d\u0438\u0446\u0442\u0432\u0456'), ('modmet', '\u041c\u043e\u0434\u0435\u043b\u0456 \u0456 \u043c\u0435\u0442\u043e\u0434\u0438 \u0443\u043f\u0440\u0430\u0432\u043b\u0456\u043d\u043d\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430\u043c\u0438'), ('ohorpr', '\u041e\u0445\u043e\u0440\u043e\u043d\u0430 \u043f\u0440\u0430\u0446\u0456 \u0432 \u0433\u0430\u043b\u0443\u0437\u0456'), ('infmod', '\u0406\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u0439\u043d\u0435 \u043c\u043e\u0434\u0435\u043b\u044e\u0432\u0430\u043d\u043d\u044f \u0442\u0435\u0445\u043d\u043e\u043b\u043e\u0433\u0456\u0439 \u0456 \u0431\u0456\u0437\u043d\u0435\u0441-\u043f\u0440\u043e\u0446\u0435\u0441\u0456\u0432 \u0432 \u0431\u0443\u0434\u0456\u0432\u043d\u0438\u0446\u0442\u0432\u0456'), ('merteh', '\u041c\u0435\u0440\u0435\u0436\u043d\u0456 \u0442\u0435\u0445\u043d\u043e\u043b\u043e\u0433\u0456\u0457')], max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u043f\u0430\u0440\u0438'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '09:00:00'), (datetime.time(10, 30), '10:30:00'), (datetime.time(12, 20), '12:20:00'), (datetime.time(13, 50), '13:50:00'), (datetime.time(15, 20), '15:20:00')], verbose_name='\u0427\u0430\u0441 \u043f\u043e\u0447\u0430\u0442\u043a\u0443 \u0437\u0430\u043d\u044f\u0442\u0442\u044f'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='type',
            field=models.CharField(choices=[('lection', '\u041b\u0435\u043a\u0446\u0456\u044f'), ('laba', '\u041b\u0430\u0431\u0430'), ('practice', '\u041f\u0440\u0430\u043a\u0442\u0438\u043a\u0430')], default='lection', max_length=32, verbose_name='\u0422\u0438\u043f \u0437\u0430\u043d\u044f\u0442\u0442\u044f'),
        ),
    ]
